### ISSUE TITLE
eScience Center Guide checklist

### ISSUE THREAD

**Issue by LourensVeen** [fair-software/howfairis#103]
As an employee of the Netherlands eScience Center, I use the [Software checklist in the eScience Center Guide](https://guide.esciencecenter.nl/#/best_practices/checklist). Does that count for the "Use a software quality checklist" criterion, and if so, can I get howfairis to recognise that somehow?

I've recently learnt that you can override howfairis' detection, but maybe there's an option to add a badge and have that recognised? That would be neater I think.

**Comment by jspaaks** [comment]
Hi Lourens,

> Does that count for the "Use a software quality checklist" criterion

I would say so.

> can I get howfairis to recognise that somehow

Not right now.

By design, the only argument that we feed `howfairis` is the URL. I don't know which repo you are referring to now, but I'm guessing that there is no way to tell from that repo that you're following the eScienceCenter Guide Checklist, at least not in an automated/generic way. If there was a badge, it would be quite easy for `howfairis` to recognize it from the README, and I'd be happy to add such functionality. I would like to point out though that such a badge would need to have an unambiguous meaning, but at the moment there are quite a few checklists to choose from:

1. https://guide.esciencecenter.nl/#/best_practices/code_review
1. https://guide.esciencecenter.nl/#/nlesc_specific/checklist
1. https://guide.esciencecenter.nl/#/nlesc_specific/checklist/checklist_prototype
1. https://guide.esciencecenter.nl/#/nlesc_specific/checklist_matrix
1. https://guide.esciencecenter.nl/#/nlesc_specific/checklist/checklist_mature
1. https://guide.esciencecenter.nl/#/nlesc_specific/checklist/checklist_prerelease

Maybe eScienceCenter should remove these in favor of the one you linked to, and additionally, the checklist that you point to is by itself multiple checklists due to the conditional inclusion of additional sublists. Finally, it would be nice if the compliance state of the checklist that you point is retained and made public in some way, similar to how the Core Infrastructures Badge Program does it e.g. https://bestpractices.coreinfrastructure.org/en/projects/3792.

**Comment by LourensVeen** [comment]
Ha, I hadn't even noticed that we had so many, and that this is getting so complicated. I guess we're getting big enough to have a bureaucracy now :-). If any of the people involved want to set up a badge/evaluation system then I'll consider putting it in my README and then howfairis can pick it up I guess. Meanwhile maybe I'll focus on keeping my users happy. Thanks for the comment!
