### ISSUE TITLE
investigate if you can use time delta between now and last readme update

### ISSUE THREAD

**Issue by jspaaks** [fair-software/howfairis#57]
this would help avoid rabbit holes like #54

**Comment by sverhoeven** [comment]
Problem of #54 was that a just edited README.md was not being retrieved by howfairis. howfairis retrieved some older cached version. 

Instead of using time delta we could also check if we can disable cache or checkout the README of the latest commit in the branch like Sven did [here](https://github.com/fair-software/howfairis/issues/54#issuecomment-739903343).

**Comment by jspaaks** [comment]
Maybe add a line to the README about delays

**Comment by eriktks** [comment]
fixed by PR #153
