### ISSUE TITLE
Verify software is on registry

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#66]
The tool just checks the badge in the README. Using a [template](https://github.com/audreyfeldroy/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.rst) it is possible to have a badge that points to nowhere.

It would be nice if it could also check if the software is also on the registry, by following the URL of the badge. 

Same goes for the zenodo and checklist badges.

**Comment by jspaaks** [comment]
Hi Stefan, thanks for this idea. It's not top of the priority list for me. I think that is partly due to the potential for a rabbit hole, e.g. let's say you write code that retrieves the URL from the readme and subsequently resolves it. There is still no guarantee that it resolved to the right package, [right](https://github.com/NLeSC/python-template/issues/57)? And the same for Zenodo, and checklists. 

A second reason is that I simply want to trust the users, and not relieve them of the responsibilty for making sure their repos are in order.

**Comment by sverhoeven** [comment]
It is the reponsibility of repo owner to setup fair badge. Howfairis should just check past badge.
