### ISSUE TITLE
Docker Hub as registry badge check

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/howfairis#67]
For example on https://github.com/sverhoeven/docker-cartodb I am using

```markdown
[![](https://images.microbadger.com/badges/version/sverhoeven/cartodb.svg)](https://hub.docker.com/r/sverhoeven/cartodb/)
```

to link to the image on Docker Hub.

It would be nice to get compliance on the registry item by adding support for https://hub.docker.com/ badges.

**Comment by jspaaks** [comment]
I considered this but rejected the idea in the end. Let me tell you my reasoning. So the purpose of putting software on registries is to promote findability (not as in 'finding it back', but rather 'discovery'), in particular through search engines. Specifically, people entering a query using their own terminology, which the search engine is then able to map to equivalent terminology from other domains, or perhaps even to some kind of structured classification like schema.org.

As far as I'm aware however, search engines are not able to do this for items on DockerHub. This is simply because doing so would require that DockerHub items have a human-readable description (basically they don't), and DockerHub items have relevant metadata (they don't).

I'd be interested to know where you stand on this.

**Comment by jspaaks** [comment]
What is and isn't a regsitry, is described here https://github.com/NLeSC/awesome-research-software-registries/tree/7f751fec9af02fac732e86bf54b5a2c1309433e3#contribute
